---
- hosts: all
  become: true
  tasks:
  - name: install update
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    package:
      name: samba
      state: latest
