---
- hosts: all
  become: true
  pre_tasks:
  - name: install update
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip
    
    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
  
  - name: start apache
    tags: apache,ubuntu,apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: change e-mail address for admin
    tags: apache,ubuntu,apache2
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Ubuntu"
    register: apache2
  
  - name: restart apache2
    tags: apache,ubuntu,apache2
    service:
      name: apache2
      state: restarted
    when: apache2.changed
  
  - name: copy default html file for site
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
