---
- hosts: all
  become: true
  pre_tasks:
  - name: install update
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 and php
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
